// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: noble/forwarding/v1/account.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/x/auth/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ForwardingAccount struct {
	*types.BaseAccount `protobuf:"bytes,1,opt,name=base_account,json=baseAccount,proto3,embedded=base_account" json:"base_account,omitempty"`
	Channel            string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Recipient          string `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	CreatedAt          int64  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Fallback           string `protobuf:"bytes,5,opt,name=fallback,proto3" json:"fallback,omitempty"`
}

func (m *ForwardingAccount) Reset()         { *m = ForwardingAccount{} }
func (m *ForwardingAccount) String() string { return proto.CompactTextString(m) }
func (*ForwardingAccount) ProtoMessage()    {}
func (*ForwardingAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d86db85ab0c667b, []int{0}
}
func (m *ForwardingAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ForwardingAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ForwardingAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ForwardingAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardingAccount.Merge(m, src)
}
func (m *ForwardingAccount) XXX_Size() int {
	return m.Size()
}
func (m *ForwardingAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardingAccount.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardingAccount proto.InternalMessageInfo

func (m *ForwardingAccount) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ForwardingAccount) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *ForwardingAccount) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ForwardingAccount) GetFallback() string {
	if m != nil {
		return m.Fallback
	}
	return ""
}

type ForwardingPubKey struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *ForwardingPubKey) Reset()      { *m = ForwardingPubKey{} }
func (*ForwardingPubKey) ProtoMessage() {}
func (*ForwardingPubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d86db85ab0c667b, []int{1}
}
func (m *ForwardingPubKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ForwardingPubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ForwardingPubKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ForwardingPubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardingPubKey.Merge(m, src)
}
func (m *ForwardingPubKey) XXX_Size() int {
	return m.Size()
}
func (m *ForwardingPubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardingPubKey.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardingPubKey proto.InternalMessageInfo

func (m *ForwardingPubKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func init() {
	proto.RegisterType((*ForwardingAccount)(nil), "noble.forwarding.v1.ForwardingAccount")
	proto.RegisterType((*ForwardingPubKey)(nil), "noble.forwarding.v1.ForwardingPubKey")
}

func init() { proto.RegisterFile("noble/forwarding/v1/account.proto", fileDescriptor_9d86db85ab0c667b) }

var fileDescriptor_9d86db85ab0c667b = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0xc7, 0xbb, 0x1f, 0x7c, 0x2a, 0x0b, 0x07, 0xac, 0x1e, 0x2a, 0xc1, 0x52, 0x39, 0x11, 0x13,
	0xba, 0x29, 0x5e, 0x0c, 0x37, 0x38, 0x98, 0x10, 0x2f, 0xa6, 0x47, 0x2f, 0x64, 0x77, 0x59, 0x4a,
	0x43, 0xe9, 0x92, 0xee, 0x16, 0xe5, 0x2d, 0x3c, 0x7a, 0xf4, 0x21, 0x7c, 0x08, 0xe3, 0x89, 0xa3,
	0x27, 0x63, 0xe0, 0x11, 0x7c, 0x01, 0xc3, 0x76, 0xa5, 0x9a, 0x78, 0x9b, 0xdf, 0x7f, 0x66, 0x76,
	0xfe, 0xb3, 0x03, 0xcf, 0x62, 0x4e, 0x22, 0x86, 0xc6, 0x3c, 0xb9, 0xc3, 0xc9, 0x28, 0x8c, 0x03,
	0xb4, 0xf0, 0x10, 0xa6, 0x94, 0xa7, 0xb1, 0x74, 0xe7, 0x09, 0x97, 0xdc, 0x3c, 0x52, 0x25, 0x6e,
	0x5e, 0xe2, 0x2e, 0xbc, 0x9a, 0x4d, 0xb9, 0x98, 0x71, 0x81, 0x70, 0x2a, 0x27, 0x68, 0xe1, 0x11,
	0x26, 0xb1, 0xa7, 0x20, 0x6b, 0xaa, 0x9d, 0x64, 0xf9, 0xa1, 0x22, 0x94, 0x81, 0x4e, 0x1d, 0x07,
	0x3c, 0xe0, 0x99, 0xbe, 0x8d, 0x32, 0xb5, 0xf9, 0x09, 0xe0, 0xe1, 0xd5, 0x6e, 0x44, 0x2f, 0x73,
	0x60, 0x0e, 0x60, 0x85, 0x60, 0xc1, 0x86, 0xda, 0x91, 0x05, 0x1c, 0xd0, 0x2a, 0x77, 0x1c, 0x57,
	0x3f, 0xa8, 0x06, 0xea, 0xe9, 0x6e, 0x1f, 0x0b, 0xa6, 0xfb, 0xfa, 0xc5, 0xd5, 0x7b, 0x03, 0xf8,
	0x65, 0x92, 0x4b, 0xa6, 0x05, 0xf7, 0xe9, 0x04, 0xc7, 0x31, 0x8b, 0xac, 0x7f, 0x0e, 0x68, 0x95,
	0xfc, 0x6f, 0x34, 0xeb, 0xb0, 0x94, 0x30, 0x1a, 0xce, 0x43, 0x16, 0x4b, 0xab, 0xa0, 0x72, 0xb9,
	0x60, 0x9e, 0x42, 0x48, 0x13, 0x86, 0x25, 0x1b, 0x0d, 0xb1, 0xb4, 0x8a, 0x0e, 0x68, 0x15, 0xfc,
	0x92, 0x56, 0x7a, 0xd2, 0xac, 0xc1, 0x83, 0x31, 0x8e, 0x22, 0x82, 0xe9, 0xd4, 0xfa, 0xaf, 0x7a,
	0x77, 0xdc, 0x75, 0x5e, 0x9f, 0xdb, 0xf5, 0xbf, 0xac, 0x6a, 0x4f, 0x83, 0xe6, 0x39, 0xac, 0xe6,
	0x4b, 0xdf, 0xa4, 0xe4, 0x9a, 0x2d, 0xcd, 0x2a, 0x2c, 0x4c, 0xd9, 0x52, 0xad, 0x5a, 0xf1, 0xb7,
	0x61, 0xb7, 0xf8, 0xf8, 0xd4, 0x30, 0xfa, 0xfe, 0xcb, 0xda, 0x06, 0xab, 0xb5, 0x0d, 0x3e, 0xd6,
	0x36, 0x78, 0xd8, 0xd8, 0xc6, 0x6a, 0x63, 0x1b, 0x6f, 0x1b, 0xdb, 0xb8, 0xbd, 0x0c, 0x42, 0x39,
	0x49, 0x89, 0x4b, 0xf9, 0x0c, 0xa9, 0x63, 0xb5, 0xb1, 0x10, 0x4c, 0x8a, 0x5f, 0x67, 0xed, 0xa0,
	0xfb, 0x9f, 0x2c, 0x97, 0x73, 0x26, 0xc8, 0x9e, 0xfa, 0xfc, 0x8b, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xe2, 0x4b, 0x5c, 0x0e, 0x07, 0x02, 0x00, 0x00,
}

func (m *ForwardingAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ForwardingAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ForwardingAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Fallback) > 0 {
		i -= len(m.Fallback)
		copy(dAtA[i:], m.Fallback)
		i = encodeVarintAccount(dAtA, i, uint64(len(m.Fallback)))
		i--
		dAtA[i] = 0x2a
	}
	if m.CreatedAt != 0 {
		i = encodeVarintAccount(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintAccount(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Channel) > 0 {
		i -= len(m.Channel)
		copy(dAtA[i:], m.Channel)
		i = encodeVarintAccount(dAtA, i, uint64(len(m.Channel)))
		i--
		dAtA[i] = 0x12
	}
	if m.BaseAccount != nil {
		{
			size, err := m.BaseAccount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAccount(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ForwardingPubKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ForwardingPubKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ForwardingPubKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintAccount(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAccount(dAtA []byte, offset int, v uint64) int {
	offset -= sovAccount(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ForwardingAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BaseAccount != nil {
		l = m.BaseAccount.Size()
		n += 1 + l + sovAccount(uint64(l))
	}
	l = len(m.Channel)
	if l > 0 {
		n += 1 + l + sovAccount(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovAccount(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovAccount(uint64(m.CreatedAt))
	}
	l = len(m.Fallback)
	if l > 0 {
		n += 1 + l + sovAccount(uint64(l))
	}
	return n
}

func (m *ForwardingPubKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovAccount(uint64(l))
	}
	return n
}

func sovAccount(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAccount(x uint64) (n int) {
	return sovAccount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ForwardingAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ForwardingAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ForwardingAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseAccount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BaseAccount == nil {
				m.BaseAccount = &types.BaseAccount{}
			}
			if err := m.BaseAccount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fallback", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fallback = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ForwardingPubKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ForwardingPubKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ForwardingPubKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAccount
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAccount(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAccount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAccount
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAccount
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAccount
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAccount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAccount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAccount = fmt.Errorf("proto: unexpected end of group")
)
