// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: noble/forwarding/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryAddress struct {
	Channel   string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Recipient string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (m *QueryAddress) Reset()         { *m = QueryAddress{} }
func (m *QueryAddress) String() string { return proto.CompactTextString(m) }
func (*QueryAddress) ProtoMessage()    {}
func (*QueryAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc601bfb5b0b1c63, []int{0}
}
func (m *QueryAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAddress.Merge(m, src)
}
func (m *QueryAddress) XXX_Size() int {
	return m.Size()
}
func (m *QueryAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAddress.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAddress proto.InternalMessageInfo

type QueryAddressResponse struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Exists  bool   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (m *QueryAddressResponse) Reset()         { *m = QueryAddressResponse{} }
func (m *QueryAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAddressResponse) ProtoMessage()    {}
func (*QueryAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc601bfb5b0b1c63, []int{1}
}
func (m *QueryAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAddressResponse.Merge(m, src)
}
func (m *QueryAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAddressResponse proto.InternalMessageInfo

func (m *QueryAddressResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryAddressResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type QueryStatsByChannel struct {
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (m *QueryStatsByChannel) Reset()         { *m = QueryStatsByChannel{} }
func (m *QueryStatsByChannel) String() string { return proto.CompactTextString(m) }
func (*QueryStatsByChannel) ProtoMessage()    {}
func (*QueryStatsByChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc601bfb5b0b1c63, []int{2}
}
func (m *QueryStatsByChannel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStatsByChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStatsByChannel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStatsByChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStatsByChannel.Merge(m, src)
}
func (m *QueryStatsByChannel) XXX_Size() int {
	return m.Size()
}
func (m *QueryStatsByChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStatsByChannel.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStatsByChannel proto.InternalMessageInfo

type QueryStatsByChannelResponse struct {
	NumOfAccounts  uint64                                   `protobuf:"varint,1,opt,name=num_of_accounts,json=numOfAccounts,proto3" json:"num_of_accounts,omitempty"`
	NumOfForwards  uint64                                   `protobuf:"varint,2,opt,name=num_of_forwards,json=numOfForwards,proto3" json:"num_of_forwards,omitempty"`
	TotalForwarded github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=total_forwarded,json=totalForwarded,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_forwarded"`
}

func (m *QueryStatsByChannelResponse) Reset()         { *m = QueryStatsByChannelResponse{} }
func (m *QueryStatsByChannelResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStatsByChannelResponse) ProtoMessage()    {}
func (*QueryStatsByChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc601bfb5b0b1c63, []int{3}
}
func (m *QueryStatsByChannelResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStatsByChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStatsByChannelResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStatsByChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStatsByChannelResponse.Merge(m, src)
}
func (m *QueryStatsByChannelResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStatsByChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStatsByChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStatsByChannelResponse proto.InternalMessageInfo

func (m *QueryStatsByChannelResponse) GetNumOfAccounts() uint64 {
	if m != nil {
		return m.NumOfAccounts
	}
	return 0
}

func (m *QueryStatsByChannelResponse) GetNumOfForwards() uint64 {
	if m != nil {
		return m.NumOfForwards
	}
	return 0
}

func (m *QueryStatsByChannelResponse) GetTotalForwarded() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TotalForwarded
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryAddress)(nil), "noble.forwarding.v1.QueryAddress")
	proto.RegisterType((*QueryAddressResponse)(nil), "noble.forwarding.v1.QueryAddressResponse")
	proto.RegisterType((*QueryStatsByChannel)(nil), "noble.forwarding.v1.QueryStatsByChannel")
	proto.RegisterType((*QueryStatsByChannelResponse)(nil), "noble.forwarding.v1.QueryStatsByChannelResponse")
}

func init() { proto.RegisterFile("noble/forwarding/v1/query.proto", fileDescriptor_fc601bfb5b0b1c63) }

var fileDescriptor_fc601bfb5b0b1c63 = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x31, 0x6f, 0x13, 0x4d,
	0x10, 0xbd, 0x73, 0xbe, 0xc4, 0xc9, 0x7e, 0x21, 0x11, 0x17, 0x17, 0x8e, 0x13, 0xce, 0xc1, 0x42,
	0xc8, 0x44, 0xf2, 0x2d, 0x36, 0x50, 0x40, 0x83, 0xe2, 0x48, 0x6e, 0x03, 0x4e, 0x47, 0x63, 0xad,
	0xcf, 0xeb, 0xcb, 0x0a, 0x7b, 0xc7, 0xdc, 0xae, 0x4d, 0xac, 0x28, 0x0d, 0x95, 0x45, 0x85, 0x44,
	0x83, 0x68, 0x48, 0x89, 0xa8, 0x52, 0xf0, 0x13, 0x28, 0x52, 0x46, 0xd0, 0x50, 0x01, 0xb2, 0x91,
	0xc2, 0xcf, 0x40, 0xb7, 0xb7, 0x67, 0x1f, 0x96, 0x23, 0x68, 0xec, 0x9b, 0x99, 0x37, 0xf3, 0xde,
	0xee, 0x9b, 0x45, 0x59, 0x0e, 0xf5, 0x16, 0xc5, 0x4d, 0xf0, 0x9f, 0x13, 0xbf, 0xc1, 0xb8, 0x87,
	0x7b, 0x45, 0xfc, 0xac, 0x4b, 0xfd, 0xbe, 0xd3, 0xf1, 0x41, 0x82, 0xb5, 0xa6, 0x00, 0xce, 0x04,
	0xe0, 0xf4, 0x8a, 0x99, 0xab, 0xa4, 0xcd, 0x38, 0x60, 0xf5, 0x1b, 0xe2, 0x32, 0xb6, 0x0b, 0xa2,
	0x0d, 0x02, 0xd7, 0x89, 0xa0, 0xb8, 0x57, 0xac, 0x53, 0x49, 0x8a, 0xd8, 0x05, 0xc6, 0x75, 0x7d,
	0x43, 0xd7, 0xd5, 0xec, 0x29, 0x92, 0xcc, 0x7a, 0x58, 0xac, 0xa9, 0x08, 0x87, 0x81, 0x2e, 0xa5,
	0x3c, 0xf0, 0x20, 0xcc, 0x07, 0x5f, 0x3a, 0xbb, 0xe9, 0x01, 0x78, 0x2d, 0x8a, 0x49, 0x87, 0x61,
	0xc2, 0x39, 0x48, 0x22, 0x19, 0x70, 0xdd, 0x93, 0x7b, 0x84, 0x96, 0x1f, 0x07, 0xd3, 0x77, 0x1a,
	0x0d, 0x9f, 0x0a, 0x61, 0xa5, 0x51, 0xd2, 0x3d, 0x20, 0x9c, 0xd3, 0x56, 0xda, 0xdc, 0x32, 0xf3,
	0x4b, 0xd5, 0x28, 0xb4, 0x36, 0xd1, 0x92, 0x4f, 0x5d, 0xd6, 0x61, 0x94, 0xcb, 0x74, 0x42, 0xd5,
	0x26, 0x89, 0x07, 0x8b, 0x83, 0x93, 0xac, 0xf1, 0xeb, 0x24, 0x6b, 0xe4, 0x18, 0x4a, 0xc5, 0x27,
	0x56, 0xa9, 0xe8, 0x00, 0x17, 0xd4, 0x2a, 0xa1, 0x24, 0x09, 0x53, 0xe1, 0xe4, 0x72, 0xfa, 0xf3,
	0xc7, 0x42, 0x4a, 0x1f, 0x40, 0x83, 0xf7, 0xa5, 0xcf, 0xb8, 0x57, 0x8d, 0x80, 0xd6, 0x35, 0xb4,
	0x40, 0x0f, 0x99, 0x90, 0x42, 0x11, 0x2e, 0x96, 0xe7, 0xdf, 0x5f, 0x9c, 0x6e, 0x9b, 0x55, 0x9d,
	0xcc, 0xdd, 0x47, 0x6b, 0x8a, 0x6a, 0x5f, 0x12, 0x29, 0xca, 0xfd, 0x5d, 0xad, 0xf4, 0xd2, 0x33,
	0xc4, 0x54, 0x0e, 0x12, 0x68, 0x63, 0x46, 0xef, 0x58, 0x6d, 0x01, 0xad, 0xf2, 0x6e, 0xbb, 0x06,
	0xcd, 0x1a, 0x71, 0x5d, 0xe8, 0x72, 0x19, 0xaa, 0xfe, 0x2f, 0x92, 0x70, 0x85, 0x77, 0xdb, 0x7b,
	0xcd, 0x1d, 0x5d, 0x8b, 0xc1, 0xb5, 0xfb, 0xa1, 0xe2, 0x29, 0x78, 0x45, 0xd7, 0xac, 0x97, 0x26,
	0x5a, 0x95, 0x20, 0x49, 0x2b, 0x82, 0xd3, 0x46, 0x7a, 0x6e, 0x6b, 0x2e, 0xff, 0x7f, 0x69, 0xdd,
	0xd1, 0x37, 0x12, 0x2c, 0x87, 0xa3, 0x97, 0xc3, 0xd9, 0x05, 0xc6, 0xcb, 0x95, 0xb3, 0x6f, 0x59,
	0xe3, 0xc3, 0xf7, 0x6c, 0xde, 0x63, 0xf2, 0xa0, 0x5b, 0x77, 0x5c, 0x68, 0x6b, 0xff, 0xf5, 0x5f,
	0x41, 0x34, 0x9e, 0x62, 0xd9, 0xef, 0x50, 0xa1, 0x1a, 0xc4, 0xdb, 0x8b, 0xd3, 0xed, 0xe5, 0x16,
	0xf5, 0x88, 0xdb, 0xaf, 0x05, 0xeb, 0x25, 0x42, 0x2d, 0x2b, 0x8a, 0xb9, 0x12, 0x11, 0x97, 0x3e,
	0x25, 0xd0, 0xbc, 0xba, 0x0a, 0xeb, 0x8d, 0x89, 0x92, 0xd1, 0x22, 0x5c, 0x77, 0x66, 0x6c, 0xb3,
	0x13, 0x77, 0x36, 0x73, 0xeb, 0xaf, 0x90, 0xe8, 0x3a, 0x73, 0x0f, 0x07, 0x01, 0xf5, 0x8b, 0x2f,
	0x3f, 0x5f, 0x27, 0xee, 0x5a, 0x25, 0x3c, 0xeb, 0x25, 0x69, 0xcf, 0xf1, 0x91, 0x36, 0xeb, 0x18,
	0x1f, 0x8d, 0xd7, 0xeb, 0xd8, 0x7a, 0x67, 0xa2, 0x95, 0x29, 0x9b, 0xf3, 0x97, 0xd3, 0xff, 0x89,
	0xcc, 0xdc, 0xfe, 0x57, 0xe4, 0x58, 0x6f, 0x71, 0xa2, 0xf7, 0xa6, 0x75, 0x63, 0xa6, 0x5e, 0x11,
	0x74, 0x4e, 0xd4, 0x96, 0xf7, 0xce, 0x86, 0xb6, 0x79, 0x3e, 0xb4, 0xcd, 0x1f, 0x43, 0xdb, 0x7c,
	0x35, 0xb2, 0x8d, 0xf3, 0x91, 0x6d, 0x7c, 0x1d, 0xd9, 0xc6, 0x93, 0x7b, 0x31, 0xc3, 0xd4, 0xa4,
	0x02, 0x11, 0x82, 0x4a, 0x11, 0x1f, 0x78, 0x18, 0x0f, 0x94, 0x87, 0xf5, 0x05, 0xf5, 0x42, 0xef,
	0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x0e, 0xdd, 0x11, 0x78, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Address(ctx context.Context, in *QueryAddress, opts ...grpc.CallOption) (*QueryAddressResponse, error)
	StatsByChannel(ctx context.Context, in *QueryStatsByChannel, opts ...grpc.CallOption) (*QueryStatsByChannelResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Address(ctx context.Context, in *QueryAddress, opts ...grpc.CallOption) (*QueryAddressResponse, error) {
	out := new(QueryAddressResponse)
	err := c.cc.Invoke(ctx, "/noble.forwarding.v1.Query/Address", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StatsByChannel(ctx context.Context, in *QueryStatsByChannel, opts ...grpc.CallOption) (*QueryStatsByChannelResponse, error) {
	out := new(QueryStatsByChannelResponse)
	err := c.cc.Invoke(ctx, "/noble.forwarding.v1.Query/StatsByChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Address(context.Context, *QueryAddress) (*QueryAddressResponse, error)
	StatsByChannel(context.Context, *QueryStatsByChannel) (*QueryStatsByChannelResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Address(ctx context.Context, req *QueryAddress) (*QueryAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Address not implemented")
}
func (*UnimplementedQueryServer) StatsByChannel(ctx context.Context, req *QueryStatsByChannel) (*QueryStatsByChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatsByChannel not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Address_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Address(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noble.forwarding.v1.Query/Address",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Address(ctx, req.(*QueryAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StatsByChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStatsByChannel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StatsByChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noble.forwarding.v1.Query/StatsByChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StatsByChannel(ctx, req.(*QueryStatsByChannel))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "noble.forwarding.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Address",
			Handler:    _Query_Address_Handler,
		},
		{
			MethodName: "StatsByChannel",
			Handler:    _Query_StatsByChannel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noble/forwarding/v1/query.proto",
}

func (m *QueryAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Channel) > 0 {
		i -= len(m.Channel)
		copy(dAtA[i:], m.Channel)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Channel)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Exists {
		i--
		if m.Exists {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryStatsByChannel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStatsByChannel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStatsByChannel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Channel) > 0 {
		i -= len(m.Channel)
		copy(dAtA[i:], m.Channel)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Channel)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryStatsByChannelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStatsByChannelResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStatsByChannelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalForwarded) > 0 {
		for iNdEx := len(m.TotalForwarded) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalForwarded[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.NumOfForwards != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.NumOfForwards))
		i--
		dAtA[i] = 0x10
	}
	if m.NumOfAccounts != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.NumOfAccounts))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Channel)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Exists {
		n += 2
	}
	return n
}

func (m *QueryStatsByChannel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Channel)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryStatsByChannelResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NumOfAccounts != 0 {
		n += 1 + sovQuery(uint64(m.NumOfAccounts))
	}
	if m.NumOfForwards != 0 {
		n += 1 + sovQuery(uint64(m.NumOfForwards))
	}
	if len(m.TotalForwarded) > 0 {
		for _, e := range m.TotalForwarded {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exists", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Exists = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStatsByChannel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStatsByChannel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStatsByChannel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStatsByChannelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStatsByChannelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStatsByChannelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumOfAccounts", wireType)
			}
			m.NumOfAccounts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumOfAccounts |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumOfForwards", wireType)
			}
			m.NumOfForwards = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumOfForwards |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalForwarded", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalForwarded = append(m.TotalForwarded, types.Coin{})
			if err := m.TotalForwarded[len(m.TotalForwarded)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
